[project]
name = "sql-insight-assistant"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "asyncpg==0.31.0",
    "chainlit==2.11.1",
    "jsonschema==4.23.0",
    "kaleido==0.2.1",
    "langchain==1.3.14",
    "langchain-anthropic==1.4.0",
    "langgraph==1.2.9",
    "pandas==2.2.3",
    "plotly==5.24.1",
    "psycopg2-binary==2.9.12",
    "python-dotenv==1.2.2",
    "sqlalchemy==2.0.51",
]
